### ISSUE TITLE
Seekbar thumb goes at start when pause

### ISSUE THREAD

**Issue by revolunet** [revolunet/VLCcontrols#1]
Need to keep the thumb at the current position when pausing

**Comment by darkius** [comment]
Does slider move for you? For me doesn't work. It takes no action when I move it. No luck with examples... The same.
I'm using 1.0.2 VLC version.

**Comment by revolunet** [comment]
depends on which kind of video you play and with which server it is server (for example, AVI+apache cannot seek). MPEG1 should work

**Comment by darkius** [comment]
I see... Well we're planing tomcat + MPEG4. Thank you for your reply.

**Comment by revolunet** [comment]
MPEG4 should work, see http://vlc.revolunet.com/git/advanced.html

**Comment by revolunet** [comment]
depends on file format and http server !
