### ISSUE TITLE
failed to load subtitle with new version

### ISSUE THREAD

**Issue by xfgavin** [revolunet/VLCcontrols#2]
Thanks for you excellent work!
I've used both the old version and the new version for VLC above 1.0. They all have this issue:
In the old version, I could load subtitles on IE kernel based browsers, but failed to load it on Firefox.
while for the new version, I couldn't load subtitle on both browsers:(
Could you fix it?
Many Thanks!

**Comment by xfgavin** [comment]
BTW, I couldn't load subtitle on your advanced example on your site too.

**Comment by revolunet** [comment]
Loading external subtitles has been disabled in VLC>=1.0 due to security restrictions

**Comment by xfgavin** [comment]
What a pity:(
Thanks
