### ISSUE TITLE
fullscreen button not function

### ISSUE THREAD

**Issue by xfgavin** [revolunet/VLCcontrols#5]
Is it a vlc problem or vlccontrols problem?
BTW, do you have plan to add full sidebars in jquery version as the old version?

Thank you very much for the excellent controls!

**Comment by revolunet** [comment]
Hi, 
Fullscreen is broken inside VLC plugin itself, sorry.
what do you mean by full sidebars ?

**Comment by xfgavin** [comment]
Hi,

Sorry for my typo, I mean full slidebars like the old version for vlc<1.1.0 which contains resolution switch, sound volumn switch etc.

**Comment by revolunet** [comment]
whats missing ? sound on/offf ?

**Comment by xfgavin** [comment]
yes, sound on/off and sound volume control according to advanced version of last vlccontrol.
